### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by jonbhanson** [alberti42/Volume-Control#15]
Thanks for your work on this wonderful app which I use on a daily basis!

After an update a week or two ago, the attached dialog pops up when I power on my machine, stating that '"Volume Control" is not authorized to respond upon events where the volume keys are pressed.'

However, when I click the "Go to Security & Privacy" button, the "Volume Control" is already checked in Accessibility as though it does have authorization.

I cannot get the app to open since it doesn't recognize that it has authorization.

Can you advise how to fix?

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/32202698/195497556-9bb4bab3-bea0-45f0-b077-1e2aec9c3bff.png">

**Comment by alberti42** [comment]
Thank you for reaching out. This already happened to me before. I suspect that the reason is that I don't have a costly subscription to Apple development program.

You can fix the problem by removing the application "Volume Control" from the Accessibility list. Before removing it, make sure to close the application. The reason is that if the application is running and  you remove it from Accessibility, you can loose control of your keyboard until you reboot your computer.

After you removed it, you can add the application there again. This should fix the problem.

Best regards
Andrea

**Comment by jonbhanson** [comment]
Thanks for the instructions, that fixed it!

Sorry, after your reply I realized that the instructions in the dialog already gave the solution if I had paid more attention.  Oops.  🫢

Thanks again for the great app!
